language: python
os:
- linux
python:
- '3.6'
- '3.7'
- '3.8'
before_install:
- python -m pip install --upgrade pip
install:
- pip install --upgrade .[lint,test,pykinect2]
stages:
- lint
- test
- deploy
script: pytest
jobs:
  include:
  - stage: lint
    script: flake8 --max-line-length 120 circum_kinect
  - stage: lint
    script: flake8 --max-line-length 120 --ignore=S101 tests
  - stage: deploy
    script: skip
    deploy:
      provider: pypi
      user: __token__
      password:
        secure: RoB/IZ191LgXy8fIvsBGs+7BaYoffSApVW80BeK6M4QSsIqvj1QzK7c8tHs82rZf70hvQya44M9riwJlju8CTpzk6rQjYDAq4KL3vmwdYDYPl0jf6YxiRYZWY+J6h6qeEc3pxFsvbkJ960cCnmPN4U+0Cgirdjn7lfj6R8VLrC+254pbclH131JFrbV4rhIbb+b2NFxLtg0fp3SCql/sSJVq4tDFn12Oyw116ZSGzhQFGKfS3EyqcWuYCGd7p67VNcn0ULjFHpUflGNRZimoKDPl6XWRSa+ElXTRLDxVhzC+igfnCpf5v5XQEqY7zWKJ98weZx4HEsrcXSJksaG28wvupTI3H+abmfI5EEVA8JOyBy27MmhQTgO70p+4LjQMd20tqay7rnboP5lpBwe2wdgfKFfmz9Eh8wFAf/LysD9VI9ozKQqaZK6okpzAzOVxUdkZDwUtbXLoO99eLxLPd0lBdaAWxRmisBpbT5Wt3Fl2XgCgw8O75p/J7laorp6lsTAElDUCcX1x7TON+z8zhDPvbqMLc4lubKfxk3PcokyRa5n3SrkydtD22+PW1RMq7RphczabEE3eiKbuortme12NoxLn4Z4osLyraL6BNZ4GposoXyr2/P1xMuD89OTbbGvuYYS7sbkXZei/cbv3bWv42hCb5VlbX/asSzOijHI=
      on:
        tags: true
      skip_existing: true
